###
GET http://localhost:8080/api/todo-tasks

### GET all with Auth
GET http://localhost:8080/api/todo-tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtdWt1bCIsImlhdCI6MTc2MDMzNTcyOSwiZXhwIjoxNzYwMzM3MTY5fQ.LxQve4xyrtZK67lYpQROYlGsomWX2hnHUh83ap235TQ

###
GET http://localhost:8080/api/todo-tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtdWt1bCIsImlhdCI6MTc2MDM3Nzc4OSwiZXhwIjoxNzYwMzc5MjI5fQ.o4J8_7rHv44U2nZ3uludiYgTpq_pNpZyYXfYW1ocZ-I

### Login to get a new token
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "mukul",
  "password": "password123"
}

###
POST http://localhost:8080/api/todo-tasks
Content-Type: application/json

{
  "task": "test",
  "done": false
}

###
PUT http://localhost:8080/api/todo-tasks/3
Content-Type: application/json

{
  "task": "sleep",
  "done": true
}

###
DELETE http://localhost:8080/api/todo-tasks

###
DELETE http://localhost:8080/api/todo-tasks/4