### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080//api/v1/todo-tasks

###
GET http://localhost:8080//api/v1/todo-tasks/1

###
POST http://localhost:8080//api/v1/todo-tasks
Content-Type: application/json

{
  "task": "Learn German",
  "done": false
}