###
GET http://localhost:8080/api/todo-tasks

###
GET http://localhost:8080/api/todo-tasks/1

###
POST http://localhost:8080/api/todo-tasks
Content-Type: application/json

{
  "task": "test",
  "done": false
}

###
PUT http://localhost:8080/api/todo-tasks/3
Content-Type: application/json

{
  "task": "sleep",
  "done": true
}

###
DELETE http://localhost:8080/api/todo-tasks

###
DELETE http://localhost:8080/api/todo-tasks/4